### --------------------------------------------------------
GET http://localhost:8080/api/products
Accept: application/json
Authorization: Bearer {{auth_token}}

### --------------------------------------------------------
POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "Widget A",
    "sku": "WGT-001"
}

### --------------------------------------------------------
GET http://localhost:8080/api/products/1
Accept: application/json
Authorization: Bearer {{auth_token}}

### --------------------------------------------------------
PATCH http://localhost:8080/api/products/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "Widget A (Updated)",
    "sku": "WGT-001-V2"
}

### --------------------------------------------------------
DELETE http://localhost:8080/api/products/1
Accept: application/json
Authorization: Bearer {{auth_token}}
